def dersmenu ():
    print("╔════════════════════════════════════════════╗")
    print("║                                            ║")
    print("║               Dersler                      ║")
    print("║                                            ║")
    print("║ Matematik                                  ║")
    print("║ Türk dili ve edebiyatı                     ║")
    print("║ Kimya                                      ║")
    print("║ Fizik                                      ║")
    print("║ Biyoloji                                   ║")
    print("║ Tarih                                      ║")
    print("║ Coğrafya                                   ║")
    print("║ İngilizce                                  ║")
    print("║ Almanca                                    ║")
    print("╚════════════════════════════════════════════╝")