def pmenu ():
    print("╔════════════════════════════════════════════╗")
    print("║                                            ║")
    print("║               Kurlar                       ║")
    print("║                                            ║")
    print("║       Dolar = 31,91 TL                     ║")
    print("║                                            ║")
    print("║                                            ║")
    print("║       Sterlin = 41,21                      ║")
    print("║                                            ║")
    print("║                                            ║")
    print("║       Euro =  40,8891                      ║")
    print("║                                            ║")
    print("║                                            ║")
    print("╚════════════════════════════════════════════╝")